### ISSUE TITLE
Two bugs!

### ISSUE THREAD

**Issue by mrniddala** [dangbroitsdon/Wall-Jump-Unofficial#18]
Hello, recently my friend (joining over GeyserMC) can't join the server anymore. I think this has nothing to do with GeyserMC.
People without the mod can't join the server anymore.

And the second thing - when I change the Jump Counter, I can't climb more at walls effectively. Please look into that too.

**Comment by dangbroitsdon** [comment]
The first one is intended, as the mod registers a Client Sided Receiver for the config syncing packets sent through the Server. So when it tries syncing the config packets for it, I'm guessing it just breaks because of them not having the mod. I'll look more deep into these when I start working on the next update. Expect Betas to come soon.

**Comment by mrniddala** [comment]
Looking forward to it 😋

**Comment by mrniddala** [comment]
Hello @dangbroitsdon, I have a new idea. What do you think about exhaustion scaling per Jump count?
Or individual settings for every Jump count.

**Comment by dangbroitsdon** [comment]
i added a multiplier for the jump count, you can't really necessarily scale like each jump different values if thats what you're trying to get at, (maybe there is a way, i just don't know it yet). the clinging problem whilst increasing jump count has been fixed now too in v1.6.0. as for the geysermc, I can't do anything about that.

**Comment by mrniddala** [comment]
Hello @dangbroitsdon - thank you so much 🥰🥰🥰

**Comment by dangbroitsdon** [comment]
No problem!
