### ISSUE TITLE
Issues connecting to the server after changing config

### ISSUE THREAD

**Issue by Anthony6996** [dangbroitsdon/Wall-Jump-Unofficial#31]
I basically enabled both enchantments for speed boost and double jump but when I try to join these errors come up:

![servererror](https://user-images.githubusercontent.com/50678776/204592344-89f5f1e6-1d6e-435c-a4a0-03ea77691cf0.png)
![walljumperror](https://user-images.githubusercontent.com/50678776/204592353-59cf2a54-718f-42cd-8a74-6b45048140d5.png)

Disabling them does fix the issue and I can connect again to the server.

**Comment by dangbroitsdon** [comment]
change the enchantment values for your instances config to true and you should be able to join

**Comment by Sebastrn** [comment]
Hello. 

Just wondering why client and server need to have the same config. I believe most of the ecosystem relies on server config being prioritized over what the client in multiplayer scenarios.

Players could change the configs locally and face the issue. Or modpacks devs need a new mod pack version just for a single config change.

**Comment by dangbroitsdon** [comment]
It's really only for enabling enchantments since Enchantments register when the client starts and server starts. The server can't force the client to register the enchantment if it was never registered to begin with, i.e. not enabled through config when the instance started since that is when registering of items and other objects occur. So it crashes with a mismatch of versions since the registry between both sides are desynced. That being said, in the future to circumvent this issue, I might just have it on by default and if people don't want it, they can turn it off, or get rid of it entirely. Still haven't decided.
